# SPDX-FileCopyrightText: 2022 leha-bot and contributors
#
# SPDX-License-Identifier: BSL-1.0 OR BlueOak-1.0.0

name: 'Check compliance'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  check:
    name: 'Check'

    runs-on: ubuntu-latest

    steps:
      - name: Fetching sources
        uses: actions/checkout@v4

      - name: Check compliance
        uses: fsfe/reuse-action@v3
