# SPDX-FileCopyrightText: 2022 leha-bot and contributors
#
# SPDX-License-Identifier: BSL-1.0 OR BlueOak-1.0.0

name: 'Lint commits'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
      - dev

jobs:
  lint:
    name: 'Lint'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint
        uses: remarkablemark/commitlint@v1
